# Generated by Django 6.1 on 2026-08-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="severity_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="severity_score",
            field=models.IntegerField(default=0),
        ),
    ]
