# Generated by Django 6.1 on 2026-08-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_complaint_severity_reason_complaint_severity_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_complaints",
                to="core.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="duplicate_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_duplicate",
            field=models.BooleanField(default=False),
        ),
    ]
